CREATE TABLE [dbo].[Cie10]
(
	[Cie10Id] SMALLINT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] CHAR(4) NOT NULL, 
    [Name] VARCHAR(500) NOT NULL, 
    [SubGroupCie10Id] SMALLINT NOT NULL, 
    CONSTRAINT [FK_Cie10_SubGroupCie10] FOREIGN KEY (SubGroupCie10Id) REFERENCES SubGroupCie10(SubGroupCie10Id)
)

GO

CREATE UNIQUE INDEX [UK_Cie10_Code] ON [dbo].[Cie10] ([Code])
