CREATE TABLE [dbo].[CUM]
(
	[CUMId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] CHAR(15) NOT NULL, 
    [Name] VARCHAR(300) NOT NULL
)

GO

CREATE UNIQUE INDEX [UK_CUM_Code] ON [dbo].[CUM] ([Code])
