CREATE TABLE [dbo].[EPS]
(
	[EPSId] SMALLINT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] CHAR(6) NOT NULL, 
    [Name] VARCHAR(100) NOT NULL
)

GO

CREATE UNIQUE INDEX [UK_EPS_Code] ON [dbo].[EPS] ([Code])
