CREATE TABLE [dbo].[FFM]
(
	[FFMId] SMALLINT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] VARCHAR(8) NOT NULL, 
    [Name] VARCHAR(50) NOT NULL
)

GO

CREATE UNIQUE INDEX [UK_FFM_Code] ON [dbo].[FFM] ([Code])
