CREATE TABLE [dbo].[GroupCie10]
(
	[GroupCie10Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(200) NOT NULL, 
    [ChapterCie10Id] INT NOT NULL, 
    CONSTRAINT [FK_GroupCie10_SubGorupCie10] FOREIGN KEY ([ChapterCie10Id]) REFERENCES ChapterCie10(ChapterCie10Id) ON UPDATE CASCADE ON DELETE CASCADE
)
