CREATE TABLE [dbo].[IUM]
(
	[IUMId] SMALLINT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] CHAR(15) NOT NULL, 
    [Name] VARCHAR(200) NOT NULL
)

GO

CREATE UNIQUE INDEX [UK_IUM_Code] ON [dbo].[IUM] ([Code])
