CREATE TABLE [dbo].[UMM]
(
	[UMMId] SMALLINT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] SMALLINT NOT NULL, 
    [Name] VARCHAR(300) NOT NULL
)

GO

CREATE UNIQUE INDEX [UK_UUM_Code] ON [dbo].[UMM] ([Code])
