CREATE TABLE [dbo].[UPR]
(
	[UPRId] SMALLINT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] SMALLINT NOT NULL, 
    [Name] VARCHAR(50) NOT NULL
)

GO

CREATE UNIQUE INDEX [UK_UPR_Code] ON [dbo].[UPR] ([Code])
