name: Compilar
on:
  push:
    branches:
      - "main"
      - "test"
      - "dev"
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:

    - name: Descarga del código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build
    runs-on: 'ubuntu-latest'

    steps:

    - name: Descarga del código
      if: ${{ github.ref_name == 'main' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Desplegar en BD Azure
      if: ${{ github.ref_name == 'main' }}
      uses: azure/sql-action@v2.2
      with:
        connection-string: 'Server=tcp:implantdent.database.windows.net,1433;Initial Catalog=implantdent;Persist Security Info=False;User ID=leandro;Password=Santi693*;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        path: 'Database/Database.sqlproj'
        action: 'publish'
        build-arguments: '-c Release'