name: Compilar
on:
  push:
    branches:
      - "main"
      - "qa"
      - "dev"
jobs:
  build:
    name: Compilar
    runs-on: 'windows-latest'

    steps:

    - name: Descarga del código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configurar msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Compilar solución
      run: msbuild Database.sln /p:Configuration=Release

  sonar:
    name: SonarQube
    needs: build
    runs-on: 'ubuntu-latest'

    steps:

    - name: Descarga del código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Desplegar
    needs: build
    runs-on: 'windows-latest'
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: Azure/sql-action@v1
      with:
        server-name: implantdent
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './bin/Relese/Database.dacpac'